name: CI

on:
  #  pull_request:
  push:
    branches:
      - development
        #      - qa
        #      - production

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: set up docker
        uses: docker/setup-buildx-action@v2

      - name: install docker dompose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: build and test
        run: |
          touch config/.env
          docker-compose build
          docker-compose up -d
          docker-compose exec -T scsb_item_updater-work_sqs_messages-1 bash -c 'bundle install --with development test && RAILS_ENV=test bundle exec rspec'
