name: CI

on:
  #  pull_request:
  push:
    branches:
      - development
        #      - qa
        #      - production

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: set up docker
        uses: docker/setup-buildx-action@v2

      - name: install docker dompose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: build and test
        run: |
          touch config/.env
          echo "ENVIRONMENT=test" >> config/.env
          echo "SQS_QUEUE_URL=https://www.example.com" >> config/.env
          echo "AWS_KEY=fake-key" >> config/.env
          echo "AWS_SECRET=fake-secret" >> config/.env
          echo "AWS_REGION=us-east-1" >> config/.env
          docker build -t scsb_item_updater:latest .
          docker-compose up -d
          docker-compose exec -T work_sqs_messages bash -c 'bundle install --with development test && RAILS_ENV=test bundle exec rspec'
